// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPqO58RYb05aFTNQcqCfIVuAtfebcxnR8',
    appId: '1:578455180403:web:e933a8e45608c478ed0606',
    messagingSenderId: '578455180403',
    projectId: 'reverpot-project',
    authDomain: 'reverpot-project.firebaseapp.com',
    storageBucket: 'reverpot-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHWbmFA4pV3EC8Dc6PrjX0oB2bdehafrI',
    appId: '1:578455180403:android:e18914086d2d86f9ed0606',
    messagingSenderId: '578455180403',
    projectId: 'reverpot-project',
    storageBucket: 'reverpot-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6tqHFZ9sQnS88rvkSj7kwog9fvUKJPkI',
    appId: '1:578455180403:ios:d3b6a6d47c7acb4eed0606',
    messagingSenderId: '578455180403',
    projectId: 'reverpot-project',
    storageBucket: 'reverpot-project.appspot.com',
    iosClientId: '578455180403-icd01obd0sqsmpq6noq65rlblfol9klk.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.revierpodFirestoreStream',
  );
}
